server:
  port: 9090

logging:
  level:
    org.springframework.security: DEBUG

#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8080/auth/user

security:
 oauth2:
   resource:
     jwt:
       keyUri: http://localhost:8080/auth/oauth/token_key